---
title: "Birmingham Ethnic Population Projection"
author: "Chung Au-Yeung"
date: today
editor: visual


server: shiny

execute:
  echo: false
  message: false
  warning: false
  fig-width: 10
  fig-height: 8

format:
  html:
    embed-resources: false
    toc: true
    toc-location: left
    number-sections: true
---

```{r setup}
#| context: setup
#| warning: false
#| message: false

library(tidyverse)
library(readr)
library(readxl)
library(bslib)
library(bcctheme)
library(scales)
library(patchwork)
```

```{r read data and function}
#| echo: false
#===========================================================
# just handy function adjusting ggsave
pixel_2_in = function(width,
                      height){
  width_in = width/96
  height_in = height/96
  
  result = c(width_in,height_in)
  return(result)
}

#============================================================

CCM_result_list = readRDS("CCM_result_list.rds")

full_component_projection = CCM_result_list[[1]]
full_population_projection = CCM_result_list[[2]]
```

## Age and ethnic profile in Birmingham

Use the controls to explore the projected population age structure by year and ethnic group.

```{r}
#| label: pyramid user interface

htmltools::tags$style(htmltools::HTML("
  .card { overflow: visible !important; }
  .card-body { overflow: visible !important; }
  .selectize-dropdown { z-index: 2000 !important; }
  .recalculating { opacity: 1 !important; }
"))
bslib::page_fillable(
  padding = 8,
  bslib::card(

   htmltools::div(
      style = "position: relative; z-index: 1050; padding: 8px 12px 0 12px;",
  
    shiny::selectInput(
      "select_ethnic",
      "Selected ethnic group",
      choices = c( "White British & Irish"="WBI", "White Other"="WHO",
                   "Mixed"="MIX",
                   "Indian"="IND", "Pakistani"="PAK", "Bangladeshi"="BAN", 
                   "Chinese"="CHI", "Other Asian"="OAS",
                   "Black African"="BLA", "Black Caribbean"="BLC", 
                   "Other Black"="OBL",
                   "Other Ethnic Group"="OTH"),
      selected = "WBI",
      multiple = FALSE
    )),
  
    bslib::card_body(
    fillable = FALSE,
    shiny::plotOutput("pyramid_plot", height = "700px")
  ),
    
  bslib::card_footer(
    shiny::sliderInput(
    "slider_year",
    "Year",
    min=as.integer(2022),
    max = as.integer(2047),
    value=as.integer(2022),
    step = 1,
    sep="",
    width = "100%",
    animate = shiny::animationOptions(interval = 800)
   )
  )
)
)

```

```{r}
#| label: pyramid-data
#| context: data
#| include: false

 pyramid_data = full_population_projection %>% 
    mutate(age = ifelse(age>=90, "90+",as.character(age)),
           age = factor(age, levels=c(as.character(0:89), "90+")),
           sex = factor(sex, levels=c("Male", "Female"))) %>% 
    group_by(year,eth_code,sex,age) %>%
    summarise(population = sum(population),
              .groups = "drop") %>% 
    mutate(population = ifelse(sex == "Male", population*-1, population))
```

```{r}
#| context: server

output$pyramid_plot = shiny::renderPlot({
  pyramid_data%>% 
    filter(eth_code == input$select_ethnic,
           year     == input$slider_year) %>% 
    ggplot(aes(y=age, x=population,fill=sex))+
    geom_col()+
    geom_step( data = pyramid_data %>% 
                 filter(eth_code == input$select_ethnic, year == 2022), 
               aes(y=age, x=population,group=sex),
               colour = "black", linewidth = 0.6,
               direction = "mid", orientation = "y")+
    scale_x_continuous(
    labels = function(x) scales::comma(abs(x)))+
    scale_y_discrete(breaks = c(as.character(seq(0, 80, 10)), "90+"))+
    scale_fill_bcc(palette = "multi")+
    ggtitle("Projected population by single year of age and sex and ethnicity \nfor Birmingham, 2022 to 2047")+
    theme_bcc(base_size = 12,
              gridline_y = F)+
    theme(legend.position = "bottom")
})

```

## Contributors to ethnic population change in Birmingham

```{r}
#| label: waterfall user interface

htmltools::tags$style(htmltools::HTML("
  .card { overflow: visible !important; }
  .card-body { overflow: visible !important; }
  .selectize-dropdown { z-index: 2000 !important; }
  .recalculating { opacity: 1 !important; }
"))
bslib::page_fillable(
  padding = 8,
  bslib::card(

   htmltools::div(
      style = "position: relative; z-index: 1050; padding: 8px 12px 0 12px;",
  
    shiny::selectInput(
      "select_ethnic_wf",
      "Selected ethnic group",
      choices = c( "White British & Irish"="WBI", "White Other"="WHO",
                   "Mixed"="MIX",
                   "Indian"="IND", "Pakistani"="PAK", "Bangladeshi"="BAN", 
                   "Chinese"="CHI", "Other Asian"="OAS",
                   "Black African"="BLA", "Black Caribbean"="BLC", 
                   "Other Black"="OBL",
                   "Other Ethnic Group"="OTH"),
      selected = "WBI",
      multiple = FALSE
    )),
  
    bslib::card_body(
    fillable = FALSE,
    shiny::plotOutput("waterfall_plot", height = "700px")
  )
)
)
```

```{r}
#| label: waterfall-data
#| context: data
#| include: false

annual_components_byeth = full_component_projection %>%
  group_by(year,eth_code) %>%
  summarise(
    births = sum(births, na.rm = TRUE),
    deaths = sum(total_deaths, na.rm = TRUE),
    natural_change =births - deaths,
    internal_in =sum(internal_in_migrants, na.rm = TRUE),
    internal_out =sum(internal_out_migrants, na.rm = TRUE),
    net_internal =internal_in - internal_out,
    international_in =sum(international_immigrants, na.rm = TRUE),
    international_out =sum(international_emigrants, na.rm = TRUE),
    net_international =international_in - international_out,
    projected_change =natural_change + net_internal +net_international,
    end_population = sum(end_population, na.rm = TRUE),
    start_pop = end_population-projected_change,
    .groups = "drop")

waterfallplot_data  = annual_components_byeth %>% 
  filter(year %in% 2023:2032) %>%
  group_by(eth_code) %>%
  summarise(Births       = sum(births),
            Deaths       = sum(deaths) * -1,
            Internal_in  = sum(internal_in),
            Internal_out = sum(internal_out) * -1,
            Immigration  = sum(international_in),
            Emigration   = sum(international_out) * -1,
            .groups = "drop") %>%
  pivot_longer(cols = -eth_code,
               values_to = "changes",
               names_to  = "details") %>%
  mutate(details = factor(details,
                          levels = c("Births", "Deaths",
                                     "Internal_in", "Internal_out",
                                     "Immigration", "Emigration"))) %>%
  arrange(eth_code, details) %>%
  group_by(eth_code) %>%                      # <- grouping FIRST
  mutate(
    end   = cumsum(changes),
    start = lag(end,default = 0),
    ypos  = rev(seq_len(n())), 
    next_ypos = lead(ypos,default = 0),# 6..1 within each group
    pad   = max(abs(changes)) * 0.03,
    label_x     = end + ifelse(changes > 0, pad, -pad),
    label_y     = ypos,
    label_hjust = ifelse(changes > 0, 0, 1),
    change_label = paste0(ifelse(changes > 0, "+", ""),
                          scales::comma(round(changes)))
  ) %>%
  ungroup() 
```

```{r}
#| context: server

output$waterfall_plot = shiny::renderPlot({
  
 waterfallplot_data_ready =waterfallplot_data %>% 
    filter(eth_code == input$select_ethnic_wf)
  
  
 start_pop = annual_components_byeth %>%
  filter(year == 2022, eth_code == input$select_ethnic_wf) %>%
  pull(end_population)

 end_pop = annual_components_byeth %>%
  filter(year == 2032, eth_code == input$select_ethnic_wf) %>%
  pull(end_population)
 
 pct_change = round((end_pop / start_pop - 1) * 100)

net_change = end_pop - start_pop
M = max(abs(waterfallplot_data_ready$changes))
M = ceiling(M / 10^(nchar(round(M)) - 2)) * 10^(nchar(round(M)) - 2) 
 

 ggplot(waterfallplot_data_ready)+
  geom_segment(aes(x = -Inf, xend = start,
                   y = ypos , yend = ypos),
               colour = "grey80",
               linewidth = 0.5)+
  geom_segment(aes(x=start, xend=end,
                   y=ypos, yend =ypos,
                   colour = changes>0),
               arrow = arrow(length = unit(8, "pt")),
               linewidth = 1)+
  geom_segment(aes(x = end,xend = end,
               y = ypos, yend = next_ypos),
               colour = "grey50",
               linewidth = 1,
               linetype = "dashed")+
  geom_segment(data=waterfallplot_data_ready %>% filter(details=="Emigration"),
               aes(x=end,xend=end,
                   y=1,yend=0),
               colour = "black",
               linewidth = 1)+
  geom_segment(x = 0,xend = 0,
               y = 6, yend = 6.8,
               colour = "black",
               linewidth = 1)+
  # 2022 population circle
  annotate("point",x = 0, y = 6.8,
           shape = 21, fill = "white",
           size = 4, stroke = 1) +
  # 2032 population circle
  annotate("point",x = net_change, y = 0,
           shape = 21, fill = "white",
           size = 4, stroke = 1)+
  # 2022 population label
  annotate("text", x = 0, y = 7.15,
        label = paste0("2022 population: ", 
                       scales::comma(round(start_pop))),
                       size = 4.5)+
  # 2032 population label
  annotate("text", x = net_change, y = -0.5,
           label = paste0("2032 projected population: \n", 
                          scales::comma(round(end_pop)),
                          " (",pct_change, "%)"),
           size = 4.5)+
  geom_text(aes(x = label_x,y = label_y,
                label = change_label,
                hjust = label_hjust,
                colour = changes > 0),
            fontface = "bold",
            size = 4,
            show.legend = FALSE)+
  scale_y_continuous(breaks = c(6.1,5.1,4.1,3.1,2.1,1.1), labels = c("Births", "Deaths",
                                              "Internal in-migration",
                                              "Internal out-migration",
                                              "Immigration",
                                              "Emigration"),
                                   limits = c(-0.6, 7.5)) +
  scale_colour_manual(values = c("TRUE" = "#2166A5",
                                 "FALSE" = "#FF5A60"),
                      guide = "none")+
  scale_x_continuous(limits = c(-M, M) * 2, labels = scales::comma)+
  labs(x="",
       y="",
       title = "How the population is projected to change, \nby cause and ethnicity")+
  theme_bcc(gridline_x = F,
            gridline_y = F,
            base_size = 12)+
  theme(axis.text.x  = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.y = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.y = element_blank())


  
  
  
  
  
  
  
  
  
})

```
